### ISSUE TITLE
Overlay doesn't work on non-flaked systems

### ISSUE THREAD

**Issue by branwright1** [nix-community/neovim-nightly-overlay#106]
Overlay doesn't work on non-flaked systems. Few days ago there was `infinite recursion in flake.nix` now it's:

 ```error: attempt to call something which is not a function but a set, at /nix/store/g8rnaxiq4vd55jah2fqy34nwjsycfzvb-nixpkgs/nixpkgs/lib/fixed-points.nix:69:67
error: attempt to call something which is not a function but a set, at /nix/store/g8rnaxiq4vd55jah2fqy34nwjsycfzvb-nixpkgs/nixpkgs/lib/fixed-points.nix:69:67

**Comment by mjlbach** [comment]
I can't reproduce:

You can try the following [nixos-shell](https://github.com/Mic92/nixos-shell) (available in nixpkgs), and it works:

```
{ pkgs, ... }: {
  boot.kernelPackages = pkgs.linuxPackages_latest;
  nixos-shell.mounts = {
    mountHome = false;
    mountNixProfile = false;
    cache = "none"; # default is "loose"
  };
  nixpkgs.overlays = [
    (import (builtins.fetchTarball {
      url = https://github.com/nix-community/neovim-nightly-overlay/archive/master.tar.gz;
    }))
  ];
  environment.systemPackages = with pkgs; [
    neovim-nightly
  ];
}
```

Can you send me a minimal nixos-shell (by modifying the above) that reproduces the program?

**Comment by branwright1** [comment]
Sorry, thats my bad, I thought it's caused by overlay but seems that after update they finally deprecated `stdenv.lib` and everything where I was using it like my shells or home-manager for gtk theme just broke because of it...
