### ISSUE TITLE
Infinite recursion encoutered

### ISSUE THREAD

**Issue by nbardiuk** [nix-community/neovim-nightly-overlay#111]
I've setup an overlay file `.config/nixpkgs/overlays/neovim.nix` with the import of this repository

```
import
  (builtins.fetchTarball {
    url = https://github.com/nix-community/neovim-nightly-overlay/archive/8398f213ace782545fd28989a332ae18a7cd29e3.tar.gz;
  })
```

It produces an infinite recursion error when I try to install

```
~ nix-shell -p neovim-nightly --show-trace
error: while evaluating the attribute 'buildInputs' of the derivation 'shell' at /nix/store/5sb83ahsb0grxh2617glqwbmzz7gzc8g-nixos-21.05pre289229.65a9923bbb9/nixos/pkgs/stdenv/generic/make-derivation.nix:201:11:
while evaluating 'getOutput' at /nix/store/5sb83ahsb0grxh2617glqwbmzz7gzc8g-nixos-21.05pre289229.65a9923bbb9/nixos/lib/attrsets.nix:486:23, called from undefined position:
while evaluating anonymous function at /nix/store/5sb83ahsb0grxh2617glqwbmzz7gzc8g-nixos-21.05pre289229.65a9923bbb9/nixos/pkgs/stdenv/generic/make-derivation.nix:152:17, called from undefined position:
while evaluating the attribute 'packages.x86_64-linux.neovim' at /nix/store/w3bmqdrirbs6fqiszf6d6krbnmgiy92j-source/contrib/flake.nix:98:18:
while evaluating the attribute 'neovim-unwrapped.overrideAttrs' at /nix/store/25s9w7cfvbakb224cl2vkac9n7l162gg-source/flake.nix:15:9:
while evaluating the attribute 'packages.x86_64-linux.neovim' at /nix/store/w3bmqdrirbs6fqiszf6d6krbnmgiy92j-source/contrib/flake.nix:98:18:
infinite recursion encountered, at /nix/store/w3bmqdrirbs6fqiszf6d6krbnmgiy92j-source/contrib/flake.nix:98:18
```

Some context:

- This setup used to work before commit https://github.com/nix-community/neovim-nightly-overlay/commit/8398f213ace782545fd28989a332ae18a7cd29e3

- I am using nixos following nixos-unstable channel.

**Comment by mjlbach** [comment]
Yeah I'm aware that is the change that seems to break the overlay for a subset of people. I'd recommend you follow the debugging steps in https://github.com/mjlbach/defaults.nvim/issues/13 to see what is going on.

**Comment by nbardiuk** [comment]
Thank you for the link it helped me to find a workaround. Turns out it fails if the overlay is in a separate file but it works using other approaches. 

I don't want to override overlays location, so I've used an ad-hock import just for one package:
```
(import <nixpkgs> {
    overlays = [
      (import (builtins.fetchTarball {
        url = https://github.com/nix-community/neovim-nightly-overlay/archive/216ece1.tar.gz;
      }))
    ];
  }).neovim-nightly
```

**Comment by mjlbach** [comment]
It might be because neovim-nightly overrides neovim which is now overridden by the overlay, not sure. I kept this for backwards company
