### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by maxdevjs** [nix-community/neovim-nightly-overlay#115]
I am missing something :)

Edited.

~~What are the prerequisites to use this overlay (`nixpkgs` overlays)?~~

~~Solved first point, I had the `nixpkgs.overlays` in an imported `.nix` file and not directly in `configuration.nix`. Does `nixpkgs.overlays` necessarily be in `configuration.nix`?~~

- Does `Cachix` depend on the same prerequisites (if they exist, after all)?

Still confused about `Cachix`. How I am supposed to use it? I followed the [instructions](https://app.cachix.org/cache/nix-community), but being able to install `neovim-nightly` only building locally 🤔

Thank you

**Comment by mjlbach** [comment]
If cachix is installed:

`cachix use nix-community`

If this doesn't work, it's a build failure (check CI) or an issue with your config (like overriding the flake inputs)
