### ISSUE TITLE
Nvim treesitter abi incorrect

### ISSUE THREAD

**Issue by AusCyberman** [nix-community/neovim-nightly-overlay#119]
Continuing https://github.com/neovim/neovim/issues/15019

**Comment by mjlbach** [comment]
How are you compiling your tree-sitter parsers? Are they built by nix? I have the following in my HM config:

```
  xdg.configFile."nvim/parser/c.so".source = "${pkgs.tree-sitter.builtGrammars.tree-sitter-c}/parser";
  xdg.configFile."nvim/parser/lua.so".source = "${pkgs.tree-sitter.builtGrammars.tree-sitter-lua}/parser";
  xdg.configFile."nvim/parser/rust.so".source = "${pkgs.tree-sitter.builtGrammars.tree-sitter-rust}/parser";
  xdg.configFile."nvim/parser/python.so".source = "${pkgs.tree-sitter.builtGrammars.tree-sitter-python}/parser";
```

The version of TS used to compile them needs to match the runtime version linked by neovim

**Comment by AusCyberman** [comment]
i have that config and the default, neither work, both say neovim is compiled with version 12 and the parser is 13

**Comment by AusCyberman** [comment]
The problem has fixed itself, after i switched to unstable from master

**Comment by mjlbach** [comment]
Teto also bumped the flake in core/contrib, which this repo wraps

**Comment by scalavision** [comment]
I still have this prob.em after a fresh install of home-manager. I get this when opening a nix file:

```
Error detected while processing FileType Autocommands for "*":
E5108: Error executing lua ...ghtly/share/nvim/runtime/lua/vim/treesitter/language.lua:33: ABI version mismatch : supported between 9 and 12, found 1
```

I have this config related to neovim:

```
  nixpkgs.overlays = [    
    (import (builtins.fetchTarball {    
      url = https://github.com/nix-community/neovim-nightly-overlay/archive/master.tar.gz;    
    }))    
  ];
```

and enabling nixpkgs: 

```
in        
{              
  programs.neovim = {
    enable = true;
#    package = unstable.pkgs.neovim;
    package = pkgs.neovim-nightly;      
};}

I tried using the unstable channel, but since I am on NixOS using the stable channel, that was not working.

It seems to me that 0.4 is still used by home-manager, is it possible to install the 0.5 release somehow, maybe using some kind of overlay? I am not that accustomed to home-manager yet. I think it could be a great option if possible, since I don't need to stay on the bleeding edge / nightly build of neovim anymore.

Thanks for making this available by the way!

**Comment by mjlbach** [comment]
> It seems to me that 0.4 is still used by home-manager, is it possible to install the 0.5 release somehow, maybe using some kind of overlay? I am not that accustomed to home-manager yet. I think it could be a great option if possible, since I don't need to stay on the bleeding edge / nightly build of neovim anymore.

This **is** the overlay. FWIW tree-sitter is *not* guaranteed to work with 0.5, and nvim-treesitter (the plugin) may break compatibility with 0.5 at any time. 0.5 should be in nixpkgs-unstable now.

You shouldn't let tree-sitter install the parsers. You should install them from nixpkgs. Make sure you clear all parsers/disable automatic parser installation with treesitter (rm -rf ~/.local/share/nvim/parse) and then add the following to HM:

```
  xdg.configFile."nvim/parser/c.so".source = "${pkgs.tree-sitter.builtGrammars.tree-sitter-c}/parser";
  xdg.configFile."nvim/parser/lua.so".source = "${pkgs.tree-sitter.builtGrammars.tree-sitter-lua}/parser";
  xdg.configFile."nvim/parser/rust.so".source = "${pkgs.tree-sitter.builtGrammars.tree-sitter-rust}/parser";
  xdg.configFile."nvim/parser/python.so".source = "${pkgs.tree-sitter.builtGrammars.tree-sitter-python}/parser";
```

**Comment by jacksonludwig** [comment]
@mjlbach when you say not to let tree-sitter install parsers, do you mean don't do stuff like `:TSInstall x` in neovim, and instead install the desired parsers as you have given in you example?
Thanks.

**Comment by mjlbach** [comment]
Yes, if you're using a non-nixos system, this will guarantee that the runtime treesitter ABI and parser's ABI match

**Comment by scalavision** [comment]
Thanks @mjlbach , seems my problem is that the version of tree-sitter is 0.19+ in nixpkgs, while the supported version is 0.18+, not sure if this this something in my plugins or in neovim itself.

**Comment by AusCyberman** [comment]
again i come back, as neovim is linked to glibc 2.32, however treesitter requires, and the current gcc version is 2.33

**Comment by AusCyberman** [comment]
i managed to just override the buildInputs to use the current nixpkgs gcc

**Comment by jacksonludwig** [comment]
> Yes, if you're using a non-nixos system, this will guarantee that the runtime treesitter ABI and parser's ABI match

Should I be able to do this for all parsers? NBD but I noticed
 ```nix
xdg.configFile."nvim/parser/comment.so".source = "${pkgs.tree-sitter.builtGrammars.tree-sitter-comment}/parser";
``` 
results in 
```
error: attribute 'tree-sitter-comment' missing
```

**Comment by marcelarie** [comment]
> i managed to just override the buildInputs to use the current nixpkgs gcc and glibc

can you show how you did this?
