### ISSUE TITLE
error while installing package

### ISSUE THREAD

**Issue by amitavaghosh1** [nix-community/neovim-nightly-overlay#137]
~/.config/nixpkgs/overlays 35s
❯ cat neovim-nightly.nix                                                                                                                                                    (1) 11:50:12
import (builtins.fetchTarball {
    url = https://github.com/nix-community/neovim-nightly-overlay/archive/master.tar.gz;
})

❯ nix-env -iA nixpkgs.neovim-nightly                                                                                                                                            11:49:34
unpacking 'https://github.com/nix-community/neovim-nightly-overlay/archive/master.tar.gz'...
unpacking 'https://github.com/edolstra/flake-compat/archive/b7547d3eed6f32d06102ead8991ec52ab0a4f1a7.tar.gz'...
unpacking 'https://api.github.com/repos/neovim/neovim/tarball/c977d8b43cd6ecf7ad756f9b064eadea79fbd604'...
unpacking 'https://api.github.com/repos/numtide/flake-utils/tarball/997f7efcb746a9c140ce1f13c72263189225f482'...
unpacking 'https://api.github.com/repos/nixos/nixpkgs/tarball/6d8215281b2f87a5af9ed7425a26ac575da0438f'...
error: infinite recursion encountered, at /nix/store/2v9vf4arnvcd01cp7p4y4vw12qpy7w1a-source/contrib/flake.nix:75:18
(use '--show-trace' to show detailed location information)

**Comment by Kranzes** [comment]
outdated and can't reproduce.
