### ISSUE TITLE
Compilation broken ( cannot find libstdc++ ) on aarch64-darwin

### ISSUE THREAD

**Issue by Sciencentistguy** [nix-community/neovim-nightly-overlay#138]
The most recent commit 1e96ff0474cbbae7e72f49739a7b09f48fe25c62 does not build on aarch64-darwin.

Log: https://gist.github.com/Sciencentistguy/fe7e4f8825f27ec0fd0322df00fb2d78

```
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.2.0, macOS 12.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.5.1`
 - channels(jamie): `"darwin, home-manager"`
 - channels(root): `"darwin, home-manager, nixpkgs-22.05pre346058.bc59ba15b64"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
 - ```

**Comment by Sciencentistguy** [comment]
Update: It does build on my desktop x86_64-linux machine

**Comment by bandithedoge** [comment]
Fixed by https://github.com/NixOS/nixpkgs/pull/156765, waiting for it to make it into unstable.

**Comment by lockejan** [comment]
Yes, wait for the PR to be available in unstable or consume directly from nixpkgs master-branch.

> if you look at nixpkgs issues, you can find one for darwin. interested in maintaining the repo ? There is no maintainer currently.

What about you @teto ?
I'm not that experienced with nix yet, but I would be interested.
