### ISSUE TITLE
Input follows non-existant input

### ISSUE THREAD

**Issue by traxys** [nix-community/neovim-nightly-overlay#140]
I have a flake that has this overlay as an input, and when used in other flake I get the`input <flake>/neovim-overlay/neovim-flake/nixpkgs follows a non-existent input "neovim-overlay/nikpkgs"`

I believe this is a known bug with flakes, could it be considered to remove the follows directive, or will it be prolematic ?

**Comment by mjlbach** [comment]
If we remove `follows`, then we'll use the pinned nixpkgs revision from the neovim contrib flake (in the neovim git repo), which means it will rarely get updated.
