### ISSUE TITLE
Enable hercules-ci instead of github actions for building and deploying to cachix

### ISSUE THREAD

**Issue by Kranzes** [nix-community/neovim-nightly-overlay#143]
CC: @mjlbach

**Comment by mjlbach** [comment]
Why?

**Comment by Kranzes** [comment]
1. Because the current github workflow/action is broken.
2. Because nix-community already has a hercules-ci set up, and hercules-ci is nicer than github actions.

**Comment by Kranzes** [comment]
>   2. I disagree

II expected a bit more out of a Nix user, to want to use a nix-native CI instead of the github runners.

**Comment by mjlbach** [comment]
I use GHA for all of my open source projects, why would I learn something additional that is nix specific? The problem was clearly not GHA, it was that nix was not compatible with the newer version of macos.

I'm also not a nix user anymore.

**Comment by nixinator** [comment]
> I'm also not a nix user anymore.

Sorry to see you go, hopefully one day you will come back with stories from docker land.

**Comment by teto** [comment]
meanwhile there is no maintainer for the repo in case either of you is interested.

**Comment by mjlbach** [comment]
FWIW I am still maintaining the repo, and just did a bunch of CI fixes

**Comment by teto** [comment]
ha but what's the point if you dont use it ? for it to work properly it's best to have someone dogfood it. Anyhow considering you already maintain much software, wouldn't you be happy to hand this one over ? Not sure how you feel about https://github.com/nix-community/neovim-nightly-overlay/issues/145 then feel free to close it then
