### ISSUE TITLE
looking for new maintainer

### ISSUE THREAD

**Issue by teto** [nix-community/neovim-nightly-overlay#145]
@mjlbach doesn't use nix anymore (know the sayting, "it's always the best who leave first") but now we have to deal with the aftermath. I dont use this repo and have no time/interest to maintain it so if anyone is interested, please reach out here.

**Comment by Kranzes** [comment]
I can maintain this repo no probelem 👋

**Comment by zimbatm** [comment]
This decision should be up to @mjlbach as he is the original maintainer. Let's wait a bit to see what he thinks about this idea. It's good that we have another potential maintainer on the line :)

**Comment by mjlbach** [comment]
I'd personally rather a member of nix-community with a track record of contributing to either neovim, neovim in nixpkgs, lua in nixpkgs, or vim in nixpkgs take over. Until there is such a person I will maintain this repo.

**Comment by adisbladis** [comment]
Quite some time has passed and this repo still doesn't have an active maintainer.

In the light of the comment by @mjlbach's wishes to distance himself from anything Neovim related (see https://www.reddit.com/r/neovim/comments/vd0vim/anyone_know_whats_going_on_with_mjldach/ichpkb4/) and no one else stepping up I'm inclined to hand over access to @Kranzes.

Let's give this a couple of days to a week, if there isn't any protest I will make @Kranzes the new maintainer.

**Comment by Kranzes** [comment]
Over a 10 days have past now

**Comment by adisbladis** [comment]
@Kranzes I've made you the repo maintainer.
