### ISSUE TITLE
no binary cache for aarch64-darwin ?

### ISSUE THREAD

**Issue by lockejan** [nix-community/neovim-nightly-overlay#150]
Hi,
I currently use this overlay on two darwin machines, x86 and arm.
I keep noticing that my arm machine never hits the binary cache, while my x86 machine always does.

Looking at the github action I wonder if there's even a arm-based builder for darwin.

Would it be possible to add one or am I missing something else?🤔

**Comment by Kranzes** [comment]
We do have one now, but all darwin builds are blocked on #176.

**Comment by Kranzes** [comment]
Fixed
