### ISSUE TITLE
nix-rebuild switch fails with newest (9f85389) master

### ISSUE THREAD

**Issue by poorpy** [nix-community/neovim-nightly-overlay#153]
Hi, while trying to run `nix-rebuild switch` I'm greeted with following error:
```
building Nix...
building the system configuration...
error: attribute 'lib' missing

       at /nix/store/5yxz55hkysfw2jh913bwb0ririlwqd1b-nixos-22.05/nixos/pkgs/applications/editors/neovim/utils.nix:117:38:

          116|         ] ++ lib.optionals (luaEnv != null) [
          117|           "--prefix" "LUA_PATH" ";" (neovim-unwrapped.lua.pkgs.lib.genLuaPathAbsStr luaEnv)
             |                                      ^
          118|           "--prefix" "LUA_CPATH" ";" (neovim-unwrapped.lua.pkgs.lib.genLuaCPathAbsStr luaEnv)
       Did you mean one of lgi, lua or luv?
(use '--show-trace' to show detailed location information)
```
removing overlay from my configuration.nix or pinning sha to `f1dd69c9e896a3f1725a0f578f9ca212558be51ed` fixes the issue.

Running with `--show-trace` produces following output: [trace.txt](https://github.com/nix-community/neovim-nightly-overlay/files/9687695/trace.txt)

**Comment by Kranzes** [comment]
Builds on master now, is that still the case for you?

**Comment by Suyashtnt** [comment]
> Builds on master now, is that still the case for you?

I just updated my nixOS + HM flake, having the same issue.

<details>
<summary>Log</summary>

dotfiles on  main [✘!] via ❄️  impure (nix-shell)
❯ nixos-rebuild switch --flake .# --show-trace
warning: Git tree '/home/tntman/dotfiles' is dirty
building the system configuration...
warning: Git tree '/home/tntman/dotfiles' is dirty
error: attribute 'lib' missing

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/pkgs/applications/editors/neovim/utils.nix:119:38:

          118|         ] ++ lib.optionals (luaEnv != null) [
          119|           "--prefix" "LUA_PATH" ";" (neovim-unwrapped.lua.pkgs.lib.genLuaPathAbsStr luaEnv)
             |                                      ^
          120|           "--prefix" "LUA_CPATH" ";" (neovim-unwrapped.lua.pkgs.lib.genLuaCPathAbsStr luaEnv)
       Did you mean one of lgi, lua or luv?

       … while evaluating the attribute 'lua.pkgs.lib.genLuaPathAbsStr'

       at /nix/store/ndp104jfnaacrm4163n4znzhi07kfir9-source/pkgs/development/interpreters/lua-5/default.nix:67:9:

           66|         withPackages = import ./with-packages.nix { inherit buildEnv luaPackages;};
           67|         pkgs = luaPackages;
             |         ^
           68|         interpreter = "${self}/bin/${executable}";

       … while evaluating 'escapeShellArg'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/strings.nix:316:20:

          315|   */
          316|   escapeShellArg = arg: "'${replaceStrings ["'"] ["'\\''"] (toString arg)}'";
             |                    ^
          317|

       … from call site

       … while evaluating 'concatMapStringsSep'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/strings.nix:111:5:

          110|     # List of input strings
          111|     list: concatStringsSep sep (map f list);
             |     ^
          112|

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/pkgs/applications/editors/neovim/utils.nix:187:21:

          186|     wrapNeovimUnstable neovim (res // {
          187|       wrapperArgs = lib.escapeShellArgs res.wrapperArgs + " " + extraMakeWrapperArgs;
             |                     ^
          188|       wrapRc = (configure != {});

       … while evaluating 'optionalString'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/strings.nix:203:5:

          202|     # String to return if condition is true
          203|     string: if cond then string else "";
             |     ^
          204|

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/pkgs/applications/editors/neovim/wrapper.nix:77:9:

           76|       ''
           77|       + optionalString (manifestRc != null) (let
             |         ^
           78|         manifestWrapperArgs =

       … while evaluating the attribute 'buildCommand' of the derivation 'neovim-master'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/pkgs/stdenv/generic/make-derivation.nix:270:7:

          269|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          270|       name =
             |       ^
          271|         let

       … while evaluating the attribute 'passAsFile'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/pkgs/build-support/buildenv/default.nix:77:5:

           76|     # XXX: The size is somewhat arbitrary
           77|     passAsFile = if builtins.stringLength pkgs >= 128*1024 then [ "pkgs" ] else [ ];
             |     ^
           78|   }

       … while evaluating the attribute 'passAsFile' of the derivation 'system-path'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/pkgs/stdenv/generic/make-derivation.nix:270:7:

          269|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          270|       name =
             |       ^
          271|         let

       … while evaluating 'check'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/types.nix:482:15:

          481|       name = "path";
          482|       check = x: isCoercibleToString x && builtins.substring 0 1 (toString x) == "/";
             |               ^
          483|       merge = mergeEqualOption;

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:757:22:

          756|       if isDefined then
          757|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                      ^
          758|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while evaluating anonymous lambda

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:757:17:

          756|       if isDefined then
          757|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                 ^
          758|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:757:12:

          756|       if isDefined then
          757|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |            ^
          758|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while evaluating the attribute 'value'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:768:27:

          767|     optionalValue =
          768|       if isDefined then { value = mergedValue; }
             |                           ^
          769|       else {};

       … while evaluating anonymous lambda

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/types.nix:492:14:

          491|       merge = loc: defs:
          492|         map (x: x.value) (filter (x: x ? value) (concatLists (imap1 (n: def:
             |              ^
          493|           imap1 (m: def':

       … from call site

       … while evaluating the attribute 'serviceDirectories' of the derivation 'dbus-1'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/pkgs/stdenv/generic/make-derivation.nix:270:7:

          269|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          270|       name =
             |       ^
          271|         let

       … while evaluating 'check'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/types.nix:482:15:

          481|       name = "path";
          482|       check = x: isCoercibleToString x && builtins.substring 0 1 (toString x) == "/";
             |               ^
          483|       merge = mergeEqualOption;

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:757:22:

          756|       if isDefined then
          757|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                      ^
          758|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while evaluating anonymous lambda

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:757:17:

          756|       if isDefined then
          757|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                 ^
          758|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:757:12:

          756|       if isDefined then
          757|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |            ^
          758|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while evaluating the attribute 'mergedValue'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:755:5:

          754|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          755|     mergedValue =
             |     ^
          756|       if isDefined then

       … while evaluating the option `environment.etc.dbus-1.source':

       … while evaluating the attribute 'value'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:720:9:

          719|     in warnDeprecation opt //
          720|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          721|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:268:72:

          267|           # For definitions that have an associated option
          268|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          269|

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/attrsets.nix:401:20:

          400|               then recurse (path ++ [name]) value
          401|               else f (path ++ [name]) value;
             |                    ^
          402|         in mapAttrs g;

       … while evaluating 'g'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/attrsets.nix:398:19:

          397|           g =
          398|             name: value:
             |                   ^
          399|             if isAttrs value && cond value

       … from call site

       … while evaluating 'escapeShellArg'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/strings.nix:316:20:

          315|   */
          316|   escapeShellArg = arg: "'${replaceStrings ["'"] ["'\\''"] (toString arg)}'";
             |                    ^
          317|

       … from call site

       … while evaluating 'concatMapStringsSep'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/strings.nix:111:5:

          110|     # List of input strings
          111|     list: concatStringsSep sep (map f list);
             |     ^
          112|

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/nixos/modules/system/etc/etc.nix:54:43:

           53|     mkdir -p "$out/etc"
           54|     ${concatMapStringsSep "\n" (etcEntry: escapeShellArgs [
             |                                           ^
           55|       "makeEtcEntry"

       … while evaluating anonymous lambda

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/nixos/modules/system/etc/etc.nix:54:33:

           53|     mkdir -p "$out/etc"
           54|     ${concatMapStringsSep "\n" (etcEntry: escapeShellArgs [
             |                                 ^
           55|       "makeEtcEntry"

       … from call site

       … while evaluating 'concatMapStringsSep'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/strings.nix:111:5:

          110|     # List of input strings
          111|     list: concatStringsSep sep (map f list);
             |     ^
          112|

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/nixos/modules/system/etc/etc.nix:54:7:

           53|     mkdir -p "$out/etc"
           54|     ${concatMapStringsSep "\n" (etcEntry: escapeShellArgs [
             |       ^
           55|       "makeEtcEntry"

       … while evaluating the attribute 'buildCommand' of the derivation 'etc'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/pkgs/stdenv/generic/make-derivation.nix:270:7:

          269|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          270|       name =
             |       ^
          271|         let

       … while evaluating the attribute 'value'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:555:44:

          554|       defnsByName' = byName "config" (module: value:
          555|           [{ inherit (module) file; inherit value; }]
             |                                            ^
          556|         ) configs;

       … while evaluating 'atDepth'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/attrsets.nix:60:17:

           59|       len = length attrPath;
           60|       atDepth = n:
             |                 ^
           61|         if n == len

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/attrsets.nix:63:39:

           62|         then value
           63|         else { ${elemAt attrPath n} = atDepth (n + 1); };
             |                                       ^
           64|     in atDepth 0;

       … while evaluating the attribute 'value'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/types.nix:552:58:

          551|         # Push down position info.
          552|         (map (def: mapAttrs (n: v: { inherit (def) file; value = v; }) def.value) defs);
             |                                                          ^
          553|       emptyValue = { value = {}; };

       … while evaluating 'dischargeProperties'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:807:25:

          806|   */
          807|   dischargeProperties = def:
             |                         ^
          808|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:736:137:

          735|         defs' = concatMap (m:
          736|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          737|         ) defs;

       … while evaluating definitions from `/nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/nixos/modules/system/etc/etc.nix':

       … while evaluating anonymous lambda

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:735:28:

          734|         # Process mkMerge and mkIf properties.
          735|         defs' = concatMap (m:
             |                            ^
          736|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:735:17:

          734|         # Process mkMerge and mkIf properties.
          735|         defs' = concatMap (m:
             |                 ^
          736|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:848:7:

          847|     in {
          848|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          849|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:749:9:

          748|       in {
          749|         values = defs''';
             |         ^
          750|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'optionalValue.value'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:767:5:

          766|
          767|     optionalValue =
             |     ^
          768|       if isDefined then { value = mergedValue; }

       … while evaluating anonymous lambda

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/types.nix:546:29:

          545|       merge = loc: defs:
          546|         zipAttrsWith (name: defs:
             |                             ^
          547|           let merged = mergeDefinitions (loc ++ [name]) elemType defs;

       … from call site

       … while evaluating anonymous lambda

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/attrsets.nix:518:24:

          517|     let f = attrPath:
          518|       zipAttrsWith (n: values:
             |                        ^
          519|         let here = attrPath ++ [n]; in

       … from call site

       … while evaluating the attribute 'value'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:555:44:

          554|       defnsByName' = byName "config" (module: value:
          555|           [{ inherit (module) file; inherit value; }]
             |                                            ^
          556|         ) configs;

       … while evaluating 'dischargeProperties'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:807:25:

          806|   */
          807|   dischargeProperties = def:
             |                         ^
          808|     if def._type or "" == "merge" then

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:736:137:

          735|         defs' = concatMap (m:
          736|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          737|         ) defs;

       … while evaluating definitions from `/nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/nixos/modules/system/etc/etc-activation.nix':

       … while evaluating anonymous lambda

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:735:28:

          734|         # Process mkMerge and mkIf properties.
          735|         defs' = concatMap (m:
             |                            ^
          736|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:735:17:

          734|         # Process mkMerge and mkIf properties.
          735|         defs' = concatMap (m:
             |                 ^
          736|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating the attribute 'values'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:848:7:

          847|     in {
          848|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          849|       inherit highestPrio;

       … while evaluating the attribute 'values'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:749:9:

          748|       in {
          749|         values = defs''';
             |         ^
          750|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'mergedValue'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:755:5:

          754|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          755|     mergedValue =
             |     ^
          756|       if isDefined then

       … while evaluating the option `system.activationScripts.etc.text':

       … while evaluating the attribute 'value'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:720:9:

          719|     in warnDeprecation opt //
          720|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          721|         inherit (res.defsFinal') highestPrio;

       … while evaluating anonymous lambda

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/modules.nix:268:72:

          267|           # For definitions that have an associated option
          268|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          269|

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/attrsets.nix:401:20:

          400|               then recurse (path ++ [name]) value
          401|               else f (path ++ [name]) value;
             |                    ^
          402|         in mapAttrs g;

       … while evaluating 'g'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/attrsets.nix:398:19:

          397|           g =
          398|             name: value:
             |                   ^
          399|             if isAttrs value && cond value

       … from call site

       … while evaluating the attribute 'text'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/nixos/modules/system/activation/activation-script.nix:9:5:

            8|   addAttributeName = mapAttrs (a: v: v // {
            9|     text = ''
             |     ^
           10|       #### Activation script snippet ${a}:

       … while evaluating 'id'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/trivial.nix:14:5:

           13|     # The value to return
           14|     x: x;
             |     ^
           15|

       … from call site

       … while evaluating 'textClosureMap'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/lib/strings-with-deps.nix:75:35:

           74|
           75|   textClosureMap = f: predefined: names:
             |                                   ^
           76|     concatStringsSep "\n" (map f (textClosureList predefined names));

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/nixos/modules/system/activation/activation-script.nix:49:9:

           48|
           49|       ${textClosureMap id (withDrySnippets) (attrNames withDrySnippets)}
             |         ^
           50|

       … while evaluating 'systemActivationScript'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/nixos/modules/system/activation/activation-script.nix:20:33:

           19|
           20|   systemActivationScript = set: onlyDry: let
             |                                 ^
           21|     set' = mapAttrs (_: v: if isString v then (noDepEntry v) // { supportsDryActivation = false; } else v) set;

       … from call site

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/nixos/modules/system/activation/activation-script.nix:137:18:

          136|       apply = set: set // {
          137|         script = systemActivationScript set false;
             |                  ^
          138|       };

       … while evaluating the attribute 'system.activationScripts.script'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/nixos/modules/system/activation/activation-script.nix:137:9:

          136|       apply = set: set // {
          137|         script = systemActivationScript set false;
             |         ^
          138|       };

       … while evaluating the attribute 'activationScript' of the derivation 'nixos-system-GAMER-PC-22.11.20220928.854fdc6'

       at /nix/store/l8p5y977qw6pi1iwd2mnfcn1rnil8cjr-source/pkgs/stdenv/generic/make-derivation.nix:270:7:

          269|     // (lib.optionalAttrs (attrs ? name || (attrs ? pname && attrs ? version)) {
          270|       name =
             |       ^
          271|         let

</details>

**Comment by poorpy** [comment]
@Kranzes I'm still happens. [Neovim 0.8.0](https://github.com/neovim/neovim/releases/tag/v0.8.0) was released yesterday maybe they introduced some breaking changes to master after that? I see that flake.nix in neovim repo was modified in [this commit](https://github.com/neovim/neovim/commit/47e60da7210209330767615c234ce181b6b67a08)

**Comment by Suyashtnt** [comment]
https://github.com/neovim/neovim/pull/20410 here is the PR that changes it

**Comment by Kranzes** [comment]
Have you tried using it without an overlay? https://github.com/Kranzes/nix-config/blob/8c352c9f690de984a302474c5142d5f94cf483d5/home/kranzes/editors.nix#L6
This works for me

**Comment by Dregorio1** [comment]
@Kranzes For me does not work your solution. I have got error `The option `programs.neovim.extraConfig' does not exist.`

**Comment by Kranzes** [comment]
> @Kranzes For me does not work your solution. I have got error `` The option `programs.neovim.extraConfig' does not exist. ``

That error is totally unrelated. You just put the the extraConfig inside the system config and not home-manager one. Also extraConfig isn't related to setting a neovim package...

**Comment by Kranzes** [comment]
Then you should create an issue on Neovim's repo or nixpkgs, as this repo doesn't do anything that might lead to that, it just consumes these 2 repos and builds them to provide a binary cache.

**Comment by Congee** [comment]
After `nix flake lock --update-input neovim-nightly nixpkgs`, I no longer see this error.
