### ISSUE TITLE
`tsserver` not working correctly after installing `neovim-nightly-overlay` from another user.

### ISSUE THREAD

**Issue by marcelarie** [nix-community/neovim-nightly-overlay#159]
I have two account in my macbook, one for work and the other is personal. 

I installed `nix` for all the users and now that I created the new account, nvim returns this when working with `tsx` files. The error messages that LSP is showing should not be there.
<img width="1520" alt="Screenshot 2022-11-09 at 11 29 49" src="https://user-images.githubusercontent.com/62728887/200806956-687b5794-e0f5-4f18-8ece-7cffa24a0f31.png">

Do you know why this happens? It seems that the Nix path is okay.

This is my home-manager neovim config:
```nix
  programs.neovim = {
    enable = true;
    package = pkgs.neovim-nightly;
    viAlias = true;
    withPython3 = true;
    extraConfig = "luafile ${homeDir}/.config/nvim/init.lua";

    extraPackages = with pkgs; [
      texlab
      sqlite
      tree-sitter
      rust-analyzer
      sumneko-lua-language-server

      perlPackages.PLS
      # perl534Packages.PerlTidy
      perl534Packages.PerlCritic
      # nodePackages.prettier
      # nodePackages.prettier_d_slim

      nodePackages.eslint_d
      nodePackages.typescript
      nodePackages.typescript-language-server
      nodePackages.intelephense
      nodePackages.vim-language-server
      nodePackages.bash-language-server
      nodePackages.yaml-language-server
      nodePackages.vscode-langservers-extracted
      nodePackages.dockerfile-language-server-nodejs
      # nodePackages.pyright
      # customNodePackages.cssmodules-language-server
    ];
  };
```

I don't know if its related but every time that I want to rebuild, `neovim-overlay` tries to create a new `init.lua` to override mine. Before it created a `init.vim` that pointed to the `lua` file.

**Info:**
Computer: Macbook M1 Max with Monterrey 
Neovim: `NVIM v0.9.0-dev-179+g5cf820f38-dirty`

**Comment by Kranzes** [comment]
Out of the scope of this repo. This repo is only meant for providing an overlay and binary cache for nightly build.
