### ISSUE TITLE
Build is failing 

### ISSUE THREAD

**Issue by leiserfg** [nix-community/neovim-nightly-overlay#164]
The patch file `neovim-build-make-generated-source-files-reproducible.patch` does not match the code in neovim but I can't find that file to fix it myself :exploding_head:

**Comment by leiserfg** [comment]
I tried building the flake in `neovim/neovim/contrib` by hand and it worked, so the issue seems to be somewhere else.

**Comment by leiserfg** [comment]
I managed to build by going back to "72ff8b1ca0331a8735c1eeaefb95c12dfe21d30a" and then bumping the neovim-flake to the latest, so the issue seems to be with ninxpkgs, should we keep that version (or use nixpkgs-stable instead of unstable?)

**Comment by nifoc** [comment]
I have submitted a patch to neovim directly: https://github.com/neovim/neovim/pull/21711

The actual cause of this is rather convoluted, so I'm not sure if the upstream patch will be accepted or not.

**Comment by nifoc** [comment]
If you're using flakes, you can work around this issue by specifying the input as follows:

```nix
inputs.neovim-nightly-overlay = {
  url = "github:nix-community/neovim-nightly-overlay";
  # Pin to a nixpkgs revision that doesn't have NixOS/nixpkgs#208103 yet
  inputs.nixpkgs.url = "github:nixos/nixpkgs?rev=fad51abd42ca17a60fc1d4cb9382e2d79ae31836";
};
```

This is obviously only meant as a temporary workaround.

**Comment by leiserfg** [comment]
Thanks for the tip.

**Comment by teto** [comment]
I would rather have this patched here  [nix-community/neovim-nightly-overlay](https://github.com/nix-community/neovim-nightly-overlay) rather than upstream. Other neovim core contributors accepted to upstream a flake.nix but I dont want to overload them with unnecessary churn.

**Comment by Kranzes** [comment]
Feel free to make a PR here.

**Comment by Kranzes** [comment]
> I would rather have this patched here [nix-community/neovim-nightly-overlay](https://github.com/nix-community/neovim-nightly-overlay) rather than upstream. Other neovim core contributors accepted to upstream a flake.nix but I dont want to overload them with unnecessary churn.

I actually think now it will be better to upstream it and update upstream's flake.lock.

**Comment by teto** [comment]
> I actually think now it will be better to upstream it and update upstream's flake.lock.

this is a bit short on explanation. The neovim repo is for neovim development, the flake over there is best effort and shouldn't be adapted to whatever patches are added in nixpkgs. I thought this was what this repo was for: check that neovim nightly works with unstable and if not:
- either pin to the latest working neovim/nixpkgs combination
- or patch neovim's declaration so that it works.

Btw the reproducibility patch has been merged and will therefore disappear from nixpkgs in the next release.

**Comment by jcdickinson** [comment]
Why was this closed?

**Comment by Kranzes** [comment]
I do not remember doing that, like at all.
