### ISSUE TITLE
Use side-by-side with stable neovim

### ISSUE THREAD

**Issue by happenslol** [nix-community/neovim-nightly-overlay#172]
Would it be possible to somehow have both a `neovim` (pointing to stable) and a `neovim-nightly` (pointing to this overlay) binary? It's already a different package and doesn't just overwrite the stable package, but I still end up with only one binary.

I've looked at #96 where this is discussed, but it seems nothing happened in the end since we still have the `neovim-nightly` package but only one `nvim` executable.

**Comment by Kranzes** [comment]
What you are looking for is to stop using the actual overlay functionality and use the package output (a real derivation) where you need it.

**Comment by happenslol** [comment]
Duh, that makes a lot of sense. Thanks!

For posterity, here's how I got it to work. I simply included the package exported from the overlay in my installed packages (home-manager):

```nix
let neovim-nightly =
  inputs.neovim-nightly-overlay.packages.${system}.neovim;
in {
  home.packages = [
    neovim-nightly

    # Add an alias so the executable is accessible:
    (writeShellScriptBin "nvim-nightly" "exec -a $0 ${neovim-nightly}/bin/nvim $@")
  ];
};

**Comment by Kranzes** [comment]
I am generally against actual overlays anyway :^). I like reproducible and cached derivations, not some unpinned Nix expressions.
