### ISSUE TITLE
Hitting /nix/store/jnp9n2x9cdvl47da3656illrd3p2qvb5-system_rplugin_manifest.patch failure again

### ISSUE THREAD

**Issue by 573** [nix-community/neovim-nightly-overlay#180]
Related #116 

Hit this this again:

>nix log /nix/store/8qhfshabngg8v29qw797bkxgasxc85d7-neovim-unwrapped-84378c4.drv
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/9l035jnj37g45npqqzsp6bil8sax38vv-a2qjd0d9qh42qysqr31i7y4v7k5hmvnn-source
source root is a2qjd0d9qh42qysqr31i7y4v7k5hmvnn-source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
applying patch /nix/store/jnp9n2x9cdvl47da3656illrd3p2qvb5-system_rplugin_manifest.patch
patching file runtime/autoload/remote/host.vim
patching file runtime/plugin/rplugin.vim
applying patch /nix/store/jbl93ifi4wm401d83pxyldhhc75ziggx-use-the-correct-replacement-args-for-gsub-directive.patch
patching file runtime/lua/vim/treesitter/query.lua
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file runtime/lua/vim/treesitter/query.lua.rej

**Comment by 573** [comment]
Workaround (I'm using flakes): Remove all `inputs.*.follows`  from my `neovim-nightly-overlay` input and let it use it's upstream inputs.

**Comment by Kranzes** [comment]
Fixed in https://github.com/nix-community/neovim-nightly-overlay/commit/88a6c749a7d126c49f3374f9f28ca452ea9419b8
