### ISSUE TITLE
Patch error again

### ISSUE THREAD

**Issue by 573** [nix-community/neovim-nightly-overlay#204]
https://github.com/nix-community/neovim-nightly-overlay/actions/runs/5133256349 (https://github.com/nix-community/neovim-nightly-overlay/commit/89fdda13efcc66d554d7afa611948265d1fe361b) unlocks https://github.com/nix-community/neovim-nightly-overlay/issues/180 again for me.

Is there some workaround involved ?

**Comment by Kranzes** [comment]
Update your nixpkgs if you're using `follows` and unstable. If you are on stable, don't use `follows` on the neovim-nightly-overlay input.

**Comment by rudesome** [comment]
recreating the `flake.lock` file, solved the issue in my nixos config
