### ISSUE TITLE
Cache for the rest of us?

### ISSUE THREAD

**Issue by musjj** [nix-community/neovim-nightly-overlay#310]
It looks like that the cache is built only for Mac:

https://github.com/nix-community/neovim-nightly-overlay/blob/5f29e24d73a84aefee3b74d6c387e2ae514c8203/.github/workflows/build.yml#L15-L17

Any plans for adding other architectures?

**Comment by Kranzes** [comment]
There is binary cache for Linux, Hercules-CI handles it.

**Comment by musjj** [comment]
Weird, I guess I'm not hitting the cache for some reason? I'm using a flake, with this in my `/etc/nixos/configuration.nix`:

```nix
nix = {
  settings = {
    substituters = [
      "https://nix-community.cachix.org"
    ];
    trusted-public-keys = [
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
  };
};
```

And I'm installing `neovim` via `home-manager` (*not* as a NixOS module). Is the setting not being applied with `home-manager`?

**Comment by musjj** [comment]
I can see `https://nix-community.cachix.org` being queried in the CLI output, so I guess it's supposed to be working. I've updated about 4-5 times now, and I don't think I've hit the cache even once. Can any Linux users confirm this?

**Comment by musjj** [comment]
The store path of my current neovim build:

```
/nix/store/9d5hqcb43djqnr9dhjf2fqhzgyq4fp7w-neovim-unwrapped-9ec0ecb
```

So I tried quering the hash directly to the cache server:

```bash
$ curl https://nix-community.cachix.org/9d5hqcb43djqnr9dhjf2fqhzgyq4fp7w.narinfo
404 - Not Found
```

So I'm not going crazy, the cache *isn't* there. I'm guessing that the cache is built on a specific `nixpkgs` revision? I'm currently using `nixos-unstable`, so maybe the cache is only targeting the stable versions?

**Comment by musjj** [comment]
Alright, I figured it out. I was blindly overriding the `nixpkgs` of all my `flake.nix` inputs using `inputs.nixpkgs.follows = "nixpkgs"`, which caused the hash to be different from the one stored in the cache server. So aggresively merging [`nixpkgs` instances](https://zimbatm.com/notes/1000-instances-of-nixpkgs) isn't *always* a good idea I guess.
