### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by mrtnvgr** [nix-community/neovim-nightly-overlay#332]
```nix
error: builder for '/nix/store/y5v26pz21gmjph5gzy74jwx9zkwa8m7y-neovim-unwrapped-a5629ab.drv' failed with exit code 1;
       last 10 log lines:
       >   Could NOT find Libvterm: Found unsuitable version "0.3", but required is at
       >   least "0.3.3" (found
       >   /nix/store/flm0i7lbg0msqgdrkpgn69hxc2brb7p0-libvterm-neovim-0.3.2/include)
       > Call Stack (most recent call first):
       >   /nix/store/5h0akwq4cwlc3yp92i84nfgcxpv5xv79-cmake-3.26.4/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
       >   cmake/FindLibvterm.cmake:23 (find_package_handle_standard_args)
       >   src/nvim/CMakeLists.txt:31 (find_package)
       >
       > 
       > -- Configuring incomplete, errors occurred!
       For full logs, run 'nix log /nix/store/y5v26pz21gmjph5gzy74jwx9zkwa8m7y-neovim-unwrapped-a5629ab.drv'.
error: 1 dependencies of derivation '/nix/store/2pl3v4jpa5hwr0xa5gxh9m05cmjsb8lp-neovim-a5629ab.drv' failed to build
```

**Comment by matt1432** [comment]
This is a temporary fix I found while we wait for this to be resolved:

Add nixpkgs-staging to your inputs: `nixpkgs-staging.url = "github:nixos/nixpkgs/staging";`

And override libvterm-neovim for the actual neovim package
```nix
neovim-flake.packages.x86_64-linux.default.override {
  libvterm-neovim = nixpkgs-staging.legacyPackages.x86_64-linux.libvterm-neovim;
};
```

**Comment by vinnymeller** [comment]
it takes longer to rebuild but you can also just add to the input for the overlay:

```nix
neovim-nightly-overlay = {
  url = "github:nix-community/neovim-nightly-overlay";
  inputs.nixpkgs.follows = "nixpkgs-staging";
};
```
with `nixpkgs-staging` being the same as in the above comment

**Comment by ryantm** [comment]
Is it possible to change the automation to only update the code if it builds successfully?

**Comment by Kranzes** [comment]
> Is it possible to change the automation to only update the flake if it builds successfully?

Sure. Idk if I want it to be blocked if Darwin fails though, I have to look into that.

**Comment by LSleutsky** [comment]
> it takes longer to rebuild but you can also just add to the input for the overlay:
> 
> ```nix
> neovim-nightly-overlay = {
>   url = "github:nix-community/neovim-nightly-overlay";
>   inputs.nixpkgs.follows = "nixpkgs-staging";
> };
> ```
> 
> with `nixpkgs-staging` being the same as in the above comment

What do you mean by the last part 

```
with `nixpkgs-staging` being the same as in the above comment
```
?

When I try to add the logic you mention in your post, I get errors that `nixpkgs-staging` doesn't exist. How exactly do you have to set the flake up to get this working with the temporary fix, cause I've tried everything and still cannot build.

Thanks!

**Comment by vinnymeller** [comment]
@LSleutsky add the line `nixpkgs-staging.url = "github:nixos/nixpkgs/staging";` below [here](https://github.com/LSleutsky/nixos/blob/a48d2ba6e0ac15234545911088ebf258461a8292/flake.nix#L5)

`nixpkgs-staging` just being nixpkgs from the staging branch (which currently has the good dependency)

**Comment by LSleutsky** [comment]
> @LSleutsky add the line `nixpkgs-staging.url = "github:nixos/nixpkgs/staging";` below [here](https://github.com/LSleutsky/nixos/blob/a48d2ba6e0ac15234545911088ebf258461a8292/flake.nix#L5)
> 
> `nixpkgs-staging` just being nixpkgs from the staging branch (which currently has the good dependency)
> 
> i would link my config but it seems i forgot to push the changes after getting it working 😄

Ahhhh gotcha, duh! Thanks for the reply, works like a charm now...!

**Comment by Kranzes** [comment]
> > Is it possible to change the automation to only update the flake if it builds successfully?
> 
> Sure. Idk if I want it to be blocked if Darwin fails though, I have to look into that.

I've made it so updates are now made in the flake-update branch and are turned into a PR that gets rebased & merged into master once neovim builds for Linux. This means that the master branch from now on should always have a working Linux package, Darwin on the other hand can still be blocker as I make its failure ignore-able in CI as Darwin tends to be much more fragile. If enough people want me to set Darwin as a blocker too, I can agree to do that, just remember that until recently Darwin was failing for multiple months while Linux was not. I am also applying the temp workaround for the current build failure.

**Comment by Kranzes** [comment]
I am keeping this issue open until this gets resolved in the next staging bump in nixpkgs

**Comment by Kranzes** [comment]
These are all basically worse than what I pushed to master earlier.

**Comment by Kranzes** [comment]
solved.
