### ISSUE TITLE
ISSUE: README.md has deprecated configuration argument

### ISSUE THREAD

**Issue by DockterTeagle** [nix-community/neovim-nightly-overlay#496]
Howdy,

The readme here has the use of the deprecated configuration argument. I understand if this is a very low priority issue, but it would be helpful to at least add a mention of how it should be done in latest versions of nix.

**Comment by Kranzes** [comment]
Can you point me to what needs to be changed (I don't use this flake like in any of the examples)? a PR would also be appreciated :)

**Comment by DockterTeagle** [comment]
my code is this
```nix
inputs = {
neovim-nightly-overlay.url = "github:nix-community/neovim-nightly-overlay"
};

outputs = {self,...}@inputs:
  let
  pkgs = import inputs.nixpkgs {
    system = "<your system name(like x86_64-linux)>" 
    overlays = [
      inputs.neovim-nightly-overlay.overlay
    ];
  };
in {
  homeConfigurations."username" = inputs.home-manager.lib.homeManagerConfiguration{
  modules = [./home.nix];
}; 
```
I removed some code which I believe is unnecessary. if this is wrong let me know.
also what is wrong is this part of the code:
```nix
configuration = {pkgs,...}:
{
  nixpkgs.overlays = overlays
};
```
the configuration argument has been deprecated, and I can do a pull request.  I guess that the correct code which follows the format of the repo code would be this:
```nix
 macbook-pro = inputs.home-manager.lib.homeManagerConfiguration {
    modules = [./home.nix];
  };
```

**Comment by DockterTeagle** [comment]
also how should I structure my commit?

**Comment by DockterTeagle** [comment]
pull request is opened let me know if I should change anything
