### ISSUE TITLE
attribute 'overlay' missing

### ISSUE THREAD

**Issue by s1n7ax** [nix-community/neovim-nightly-overlay#531]
After one of the recent (within a month I'm guessing) I'm getting this error.

```
error:
       … while evaluating a branch condition

         at /nix/store/z71lmgd0ydfnax1b13zbrls5idf1y7ak-source/lib/lists.nix:125:9:

          124|       fold' = n:
          125|         if n == len
             |         ^
          126|         then nul

       … while calling the 'length' builtin

         at /nix/store/z71lmgd0ydfnax1b13zbrls5idf1y7ak-source/lib/lists.nix:123:13:

          122|     let
          123|       len = length list;
             |             ^
          124|       fold' = n:

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'overlay' missing

       at /nix/store/yf0c9fglcjhsq68xvw0n3qmk2ij4z2n2-source/flake.nix:23:20:

           22|       #--------------------------------------------------------------------#
           23|       overlays = [ inputs.neovim-nightly-overlay.overlay ];
             |                    ^
           24|
       Did you mean overlays?
```

https://github.com/s1n7ax/dothome/blob/33623dec9a3921fe0e94471034e4e3198718c898/.config/home-manager/flake.nix#L16

**Comment by dgabka** [comment]
It's `neovim-nightly-overlay.overlays.default` now. See #525

**Comment by s1n7ax** [comment]
@dgabka I'm still getting `NVIM v0.10.0` version. Are there any other property I have to use to get the nightly?

**Comment by dgabka** [comment]
@s1n7ax I got nightly right away. Don't know about any other properties? Did you update flake and rebuild?

**Comment by s1n7ax** [comment]
Yes. I ran `cd ~/.config/home-manager && nix flake update && home-manager --impure switch --refresh`.

I have corrected the property
https://github.com/s1n7ax/dothome/blob/1b45ac3157702f6690a5957c5decc6098ab5085a/.config/home-manager/flake.nix?plain=1#L23

Adding it to `nixpkgs.overlays` here
https://github.com/s1n7ax/dothome/blob/1b45ac3157702f6690a5957c5decc6098ab5085a/.config/home-manager/profile/desktop/configuration.nix?plain=1#L37

Am I doing anything wrong?

**Comment by dgabka** [comment]
Sorry, I am just getting started with nix myself, so I won't be of much more help here, but it seems alright to me.

**Comment by comfysage** [comment]
[here](https://github.com/s1n7ax/dothome/blob/main/.config%2Fhome-manager%2Fsystem%2Fapplications%2Fneovim.nix#L2) you're installing neovim using:
```nix
programs.neovim = {
  enable = true;
  ...
};
```
this installs `pkgs.neovim-unwrapped` by default.
to use the overlay you have to use `pkgs.neovim`.
```diff
programs.neovim = {
  enable = true;
  package = pkgs.neovim;
  ...
};
```

**Comment by s1n7ax** [comment]
`pkgs.neovim` fixed it. Thanks
