### ISSUE TITLE
[NOTICE] Upstream breaking changes

### ISSUE THREAD

**Issue by willruggiano** [nix-community/neovim-nightly-overlay#533]
If you've recently updated your system to depend on a recent commit (at least https://github.com/nix-community/neovim-nightly-overlay/commit/d659352f0a68717fa1d02391a74269067fccedf7) of this repository, you might encounter an error like that seen in #521. If you do, **ensure that you have a recent nixpkgs package set** (at least https://github.com/NixOS/nixpkgs/commit/d5786c1b5dd2d560724b78f3ce51f1f4ef52d053).

There were a number of commits introduced upstream (i.e. nixpkgs) where breaking changes (and subsequent reverts) were made to the packaging of neovim-unwrapped (particularly as it relates to bundling tree-sitter parsers), for example; https://github.com/NixOS/nixpkgs/commit/76ef4c7888c52bd4eed566011c24da9eb437a3c8.

This advice applies particularly to those of you which override the nixpkgs input for this flake, e.g.

```nix
inputs.neovim-nightly-overlay.inputs.nixpkgs.follows = "your nixpkgs";
```

as well as those of you that use the flake's default overlay, e.g.

```nix
{
  nixpkgs.overlays = [
    inputs.neovim-nightly-overlay.overlays.default
  ];
}
```

**Comment by GaetanLepage** [comment]
@willruggiano should we know mark this as resolved ?

**Comment by willruggiano** [comment]
I would keep it open for a bit longer. There's been a few references to it recently

**Comment by GaetanLepage** [comment]
> I would keep it open for a bit longer. There's been a few references to it recently

Sure !

**Comment by matejc** [comment]
I am unsure if this is the same issue, but I get 
```
error:
       … while calling the 'head' builtin

         at /nix/store/mj0rlzph9xh8x3jj8bq4rqn0zql15w68-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/mj0rlzph9xh8x3jj8bq4rqn0zql15w68-source/lib/modules.nix:816:9:

          815|     in warnDeprecation opt //
          816|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          817|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'unwrapped' missing

       at /nix/store/mj0rlzph9xh8x3jj8bq4rqn0zql15w68-source/pkgs/by-name/ne/neovim-qt-unwrapped/package.nix:22:5:

           21|   buildInputs = [
           22|     neovim.unwrapped # only used to generate help tags at build time
             |     ^
           23|     libsForQt5.qtbase
```
while using this flake's nixpkgs

**Comment by willruggiano** [comment]
Hard to tell without seeing how you're using the flake. It looks like you're trying to install neovim-qt?
