### ISSUE TITLE
Constant full CPU core load on x86-64 darwin

### ISSUE THREAD

**Issue by konradmalik** [nix-community/neovim-nightly-overlay#538]
Hey,
after updating this repo to this commit (and later): https://github.com/nix-community/neovim-nightly-overlay/commit/bd7497d3a7eadddebd9f547e4aab7ea204c892a3
neovim on x86_64-darwin for some reason consumes one full CPU core constantly.
Tried with both, current state of this flake, and overriding inputs to the newest neovim-src and nixpkgs.

Facts I know:
- started happening after https://github.com/nix-community/neovim-nightly-overlay/commit/bd7497d3a7eadddebd9f547e4aab7ea204c892a3
- happens only on darwin, while linux (at least arm64) works fine
- pre-build binaries from neovim don't have this issue, that's why I assume the problem is either here or in nixpkgs
- should be reproducible via `nix run` here: https://github.com/konradmalik/neovim-flake and opening `flake.nix`, readme, or some lua file
- to try upstream neovim binary - `nix build` my flake, copy the script `cat ./result/bin/nvim | pbcopy`, create new script like `run.sh`, paste the script and change the last line to call the unpacked upstream neovim binary. All works fine then.
- cpu consumption starts only after opening some file or even viewing it via telescope, that's why my first thought was - something wrong with tree-sitter?
- the bug does not prevent from using neovim normally, it's not blocking
- all seems ok if I just open neovim and don't do anything to exit start screen
- all seems ok as well if I don't use any plugins at all and then open a file
- additionally, when the "cpu consumption" starts, after I exit nvim, terminal looks like something killed nvim, it's not cleared properly, see the below screenshot

Can it be something with tree-sitter?

Filing the issue here but I'm not sure if the issue is here or in nixpkgs. 
Happy to provide more info and help in any way.

<img width="1680" alt="image" src="https://github.com/nix-community/neovim-nightly-overlay/assets/13033392/e215d037-ed9b-416d-a82c-2bfecf8454f2">

**Comment by willruggiano** [comment]
So, immediately upon opening neovim your cpu's pegged? Are there any clues in `:checkhealth`? What about Activity Monitor, any clues in there or does it just claim "neovim" is the culprit?

**Comment by konradmalik** [comment]
Not immediately after opening. Only after opening any file, or after opening file preview via telescope. That's why the first thing that came to my mind was treesitter but not sure how to check that.

Activity monitor just shows "nvim - 99.9" in the cpu column and laptop gets hot.

Checkhealth shows nothing suspicious but I'll post both reports later (compiled and binary from neovim repo), maybe it'll show some differences, because one works ok, the other not.

**Comment by willruggiano** [comment]
I see. Unfortunately I do not have a macOS to try and repro on my own.

From what you've described, I am suspicious of the dependencies for which we overriding derivation inputs. If you have time and are so inclined, could you try commenting out the overridden dependencies here (around L50); https://github.com/nix-community/neovim-nightly-overlay/blob/master/flake/packages/neovim.nix

Let me know if you need help forking/cloning this repo and/or getting your neovim flake to point at your local copy.

**Comment by konradmalik** [comment]
Thanks for a good lead!
After trial and error, the cause seems to be: `libuv` (after commenting it out in overrides, nvim compiled from this repo behaves normally).
Here's a workaround that fixes the issue in my flake: https://github.com/konradmalik/neovim-flake/commit/3d71a41a990c279204ba8dfe5c7b6749edc3d7ba

But I'm not sure how we should proceed in this repo to fix it. Any suggestions?
What's weird is that both nixpkgs and neovim deps.txt file seem to have the same libuv version (1.48), but they still behave differently on darwin.

**Comment by willruggiano** [comment]
Interesting! Although not totally surprising. You said the binary release (or build) for the same upstream commit does _not_ exhibit this cpu problem? I guess we need to go dig through neovim's cmake code :D

Anyways, thanks for filing this issue! I can take it from here. Will commit a temporary fix until I have time to investigate what could be the real root cause here.

**Comment by konradmalik** [comment]
Hmm, so replacing `src` in libuv with the nixpkgs one:
```
            libuv = pkgs.libuv.overrideAttrs {
              src = pkgs.fetchFromGitHub {
                owner = "libuv";
                repo = "libuv";
                rev = "v1.48.0";
                hash = "sha256-U68BmIQNpmIy3prS7LkYl+wvDJQNikoeFiKh50yQFoA=";
              };
            };
```
also fixes the issue.

While explicitly providing the neovim's one:
```
            libuv = pkgs.libuv.overrideAttrs {
              src = pkgs.fetchurl {
                url = "https://github.com/libuv/libuv/archive/v1.48.0.tar.gz";
                sha256 = "8c253adb0f800926a6cbd1c6576abae0bc8eb86a4f891049b72f9e5b7dc58f33";
              };
            };
```
brings the issue back.

Does it mean that v1.48.0 used in nixpkgs (downloaded from source directly) is not the same as v1.48.0 locked in neovim's repo (downloaded from the released tarball)?
And then, I still cannot understand why a pre-built binary from neovim works fine...

**Comment by konradmalik** [comment]
I've cloned libuv locally, checked-out the v1.48.0 tag, downloaded the v1.48.0 release tarball, and diffed both sources:
```
❯ diff -qrN libuv-repo-1.48/ libuv-archive-1.48/
Files libuv-repo-1.48/.git/HEAD and libuv-archive-1.48/.git/HEAD differ
Files libuv-repo-1.48/.git/config and libuv-archive-1.48/.git/config differ
Files libuv-repo-1.48/.git/description and libuv-archive-1.48/.git/description differ
Only in libuv-repo-1.48/.git: fsmonitor--daemon.ipc
Files libuv-repo-1.48/.git/hooks/applypatch-msg.sample and libuv-archive-1.48/.git/hooks/applypatch-msg.sample differ
Files libuv-repo-1.48/.git/hooks/commit-msg.sample and libuv-archive-1.48/.git/hooks/commit-msg.sample differ
Files libuv-repo-1.48/.git/hooks/fsmonitor-watchman.sample and libuv-archive-1.48/.git/hooks/fsmonitor-watchman.sample differ
Files libuv-repo-1.48/.git/hooks/post-update.sample and libuv-archive-1.48/.git/hooks/post-update.sample differ
Files libuv-repo-1.48/.git/hooks/pre-applypatch.sample and libuv-archive-1.48/.git/hooks/pre-applypatch.sample differ
Files libuv-repo-1.48/.git/hooks/pre-commit.sample and libuv-archive-1.48/.git/hooks/pre-commit.sample differ
Files libuv-repo-1.48/.git/hooks/pre-merge-commit.sample and libuv-archive-1.48/.git/hooks/pre-merge-commit.sample differ
Files libuv-repo-1.48/.git/hooks/pre-push.sample and libuv-archive-1.48/.git/hooks/pre-push.sample differ
Files libuv-repo-1.48/.git/hooks/pre-rebase.sample and libuv-archive-1.48/.git/hooks/pre-rebase.sample differ
Files libuv-repo-1.48/.git/hooks/pre-receive.sample and libuv-archive-1.48/.git/hooks/pre-receive.sample differ
Files libuv-repo-1.48/.git/hooks/prepare-commit-msg.sample and libuv-archive-1.48/.git/hooks/prepare-commit-msg.sample differ
Files libuv-repo-1.48/.git/hooks/push-to-checkout.sample and libuv-archive-1.48/.git/hooks/push-to-checkout.sample differ
Files libuv-repo-1.48/.git/hooks/sendemail-validate.sample and libuv-archive-1.48/.git/hooks/sendemail-validate.sample differ
Files libuv-repo-1.48/.git/hooks/update.sample and libuv-archive-1.48/.git/hooks/update.sample differ
Files libuv-repo-1.48/.git/index and libuv-archive-1.48/.git/index differ
Files libuv-repo-1.48/.git/info/exclude and libuv-archive-1.48/.git/info/exclude differ
Files libuv-repo-1.48/.git/logs/HEAD and libuv-archive-1.48/.git/logs/HEAD differ
Files libuv-repo-1.48/.git/logs/refs/heads/v1.x and libuv-archive-1.48/.git/logs/refs/heads/v1.x differ
Files libuv-repo-1.48/.git/logs/refs/remotes/origin/HEAD and libuv-archive-1.48/.git/logs/refs/remotes/origin/HEAD differ
Files libuv-repo-1.48/.git/objects/pack/pack-47d03c1b5b99f0dc90968d5008cc78e6bc27b320.idx and libuv-archive-1.48/.git/objects/pack/pack-47d03c1b5b99f0dc90968d5008cc78e6bc27b320.idx differ
Files libuv-repo-1.48/.git/objects/pack/pack-47d03c1b5b99f0dc90968d5008cc78e6bc27b320.pack and libuv-archive-1.48/.git/objects/pack/pack-47d03c1b5b99f0dc90968d5008cc78e6bc27b320.pack differ
Files libuv-repo-1.48/.git/objects/pack/pack-47d03c1b5b99f0dc90968d5008cc78e6bc27b320.rev and libuv-archive-1.48/.git/objects/pack/pack-47d03c1b5b99f0dc90968d5008cc78e6bc27b320.rev differ
Files libuv-repo-1.48/.git/packed-refs and libuv-archive-1.48/.git/packed-refs differ
Files libuv-repo-1.48/.git/refs/heads/v1.x and libuv-archive-1.48/.git/refs/heads/v1.x differ
Files libuv-repo-1.48/.git/refs/remotes/origin/HEAD and libuv-archive-1.48/.git/refs/remotes/origin/HEAD differ
```

I'm so confused
