### ISSUE TITLE
Investigate the root cause of #538

### ISSUE THREAD

**Issue by willruggiano** [nix-community/neovim-nightly-overlay#540]
#538

**Comment by GaetanLepage** [comment]
Is this still happening ?

**Comment by willruggiano** [comment]
> Is this still happening ?

Lmao. I've been too busy at the day job. So... closed.

**Comment by petertriho** [comment]
@GaetanLepage I'm on `aarch64-darwin` but it looks like [141f2db491ab484a2372ee8368fcd3a31422ec2f ](https://github.com/nix-community/neovim-nightly-overlay/commit/141f2db491ab484a2372ee8368fcd3a31422ec2f) is causing the cpu spikes (and memory leaks) issue again.
