### ISSUE TITLE
Nix displaying a warning about structuredAttrs and disallowedRequisites

### ISSUE THREAD

**Issue by PartyWumpus** [nix-community/neovim-nightly-overlay#579]
`warning: In a derivation named 'neovim-unwrapped-nightly', 'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites'; use 'outputChecks.<output>.disallowedRequisites' instead` (appears next to the constantly present `warning: Git tree '..' is dirty` error)

This appears to have been directly caused by https://github.com/NixOS/nix/pull/10884 which was done because of https://github.com/NixOS/nix/issues/10856

Presumably the `disallowedReferences` it's talking about are [here](https://github.com/nix-community/neovim-nightly-overlay/blob/b6b51915180e6d2eac488d6f882e4ba36bad380d/flake/packages/neovim-debug.nix#L18C5-L18C25), but i'm not sure what `structuredAttrs` is referring to.

I'm not sure if this is an actual problem or not, but I thought it would be worth letting you know at least.

**Comment by willruggiano** [comment]
Thanks for the report. I think this has to do with how upstream (nixpkgs) defines the derivation, if my recollection is correct. So, might be more suited to an issue there. Regardless I will check and open an upstream issue if one is warranted

**Comment by Gerg-L** [comment]
PR made here: https://github.com/NixOS/nixpkgs/pull/330026
