### ISSUE TITLE
error: function 'anonymous lambda' called with unexpected argument 'libiconv'

### ISSUE THREAD

**Issue by HeitorAugustoLN** [nix-community/neovim-nightly-overlay#685]
Starting from https://github.com/NixOS/nixpkgs/commit/bed551533cef8e811bf40858fad45597e8f1c685, this error occurs when trying to run the neovim-nightly
![image](https://github.com/user-attachments/assets/27c6026d-c43b-44c8-8328-25606ebaa23f)

**Comment by HeitorAugustoLN** [comment]
Looks like this will be fixed in #682

**Comment by GaetanLepage** [comment]
> Looks like this will be fixed in #682

Yes, we are still waiting for `nixpkgs-unstable` to jump to a newer revision. As soon as this happens, the update will be merged in the overlay.

**Comment by GaetanLepage** [comment]
Fixed in https://github.com/nix-community/neovim-nightly-overlay/pull/682
