### ISSUE TITLE
Swapping the cachix cache from mjlbach to nix-community

### ISSUE THREAD

**Issue by mjlbach** [nix-community/neovim-nightly-overlay#85]
cc @Mic92 

I'm not sure what needs to be done on my end, I can change the github action to point to cachix but don't know how to add the nix-community repo to the GHA secrets.

**Comment by Mic92** [comment]
cc @domenkozar, @zimbatm or @adisbladis can we get the secret for the nix-community cachix or should we use a different cache here?

**Comment by domenkozar** [comment]
I'll leave it to @zimbatm, not sure how he configured it. Could generate another cache token :)

**Comment by mjlbach** [comment]
Fixed
