### ISSUE TITLE
Use neovim's bundled flake

### ISSUE THREAD

**Issue by mjlbach** [nix-community/neovim-nightly-overlay#89]
@teto Added a [flake](https://github.com/neovim/neovim/blob/master/contrib/flake.nix) to neovim contrib, we should build from that, instead of using our own. It also provides some nice outputs, like neovim-developer and neovim-debug which are useful to those of us that also contribute to neovim.

**Comment by teto** [comment]
I wonder what to do with this, should it get removed or used to showcase some neovim wrapped setups ? your call, I dont intend to contribute. Just wanted to make sure that we dont duplicate work on that overlay.

**Comment by mjlbach** [comment]
> I dont intend to contribute

😭 

>I wonder what to do with this

I'm working on that PR to update the neovim flake (currently, it *hates* macos), but I have a version of *this* flake that is a wrapper around the one in neovim. It's main purpose is to override the inputs such that the nixpkgs input is determinsitic. The other point of this repo will be providing the CI/storing the cachix key for nix community (which we can't do in the neovim repo obv), and providing the flake-compat wrapper so that non-flakes users can still use the overlay.

 The advantage of overriding/bundling the inputs, compared to emacs overlay for example which uses your *current* nixpkgs as input, you can check out and fetch neovim from the cachix binary cache until it's garbage collected. This makes bisects for regression testing very fast on nix. The disadvantage being a slight increase in closure size.

**Comment by teto** [comment]
> (currently, it hates macos), 

yes I was pretty sure the first contribution would be multiplatform support ^^ Neovim is pretty fast to build but a nix-community cache amortizes the setup cost. Looks like you have several ideas so this repo is useful :)

I want the neovim flake to be low maintainance. The other contributors agreed to my whim of upstreaming the flake so I dont want them to be dealing with too many nix PRs, This one here can evolve faster.

**Comment by teto** [comment]
what could be helpful is for this repository to contain some neovim configurations that would allow for users to check their config against a reference one. 
So we could take the lspconfig minimal.vim, generate a config with pkgs/applications/editors/neovim/utils.nix and provide a package so that one can run `nix run neovim-nightly-overlay#test-minimal-lspconfig-rust` etc.
