### ISSUE TITLE
Not installing Nightly

### ISSUE THREAD

**Issue by breuerfelix** [nix-community/neovim-nightly-overlay#91]
nvim --version still outputs 0.4.4

here i do the overlay and 5 lines below i install neovim-nightly as a systempackage:  
https://github.com/breuerfelix/nixos/blob/d96df2f7097188979ac637549f7559afc6b3f5f8/configuration.nix#L63

this is my home manager configuration (note that i use globalPackages, thats why i have to do the override in the system config):  
https://github.com/breuerfelix/nixos/blob/d96df2f7097188979ac637549f7559afc6b3f5f8/users.nix#L36

this is my neovim config in home manager:  
https://github.com/breuerfelix/nixos/blob/main/shell/vim.nix

am i doing something wrong ? the whole repo is my current setup :) but i can provide more info if needed!

btw thanks for the package i am really looking forward to nightly! wanna try out all this LSP stuff :)

**Comment by mjlbach** [comment]
You are welcome. You are using the home-manager module and need to substitute the package. Add this line:

```
package = pkgs.neovim-nightly;
```

below 

```
enabled = true;
```

here:

https://github.com/breuerfelix/nixos/blob/d96df2f7097188979ac637549f7559afc6b3f5f8/shell/vim.nix#L3

**Comment by breuerfelix** [comment]
![image](https://user-images.githubusercontent.com/36931468/106783001-1d97cc80-664b-11eb-9d05-daadf392966d.png)

you are so right! can't believe that i forgot about that ... thanks a lot :) now its all about getting rid of coc ... :)

**Comment by mjlbach** [comment]
Hopefully I can answer those questions too: https://github.com/neovim/nvim-lspconfig/blob/master/README.md

**Comment by breuerfelix** [comment]
thanks ! that will be my good night lecture for the next days :) glad that there are a lot of *.vim and *.lua files out there. including yours :)
