### ISSUE TITLE
'pkgs.neovim-nightly ' not found

### ISSUE THREAD

**Issue by blissdev** [nix-community/neovim-nightly-overlay#92]
I suspect this is because I'm a NixOS noob, but here we go.

I added the code provided to my `configuration.nix`. 

I then ran `sudo nixos-rebuild switch`. When I then run the suggested `nix-env -iA pkgs.neovim-nightly`, I get the following error:

```
[demo@nixos:~]$ nix-env -iA pkgs.neovim-nightly
error: attribute 'pkgs' in selection path 'pkgs.neovim-nightly' not found
```

Any ideas?

**Comment by mjlbach** [comment]
That's because you are trying to install imperatively which isn't picking up on the overlays passed to the nixpkgs attribute set used to build your nixos config (but which isn't applied to your user channels). If you want to install with nix-env, I would add the overlay to your ~/.config/nixpkgs/overlays folder. I would recommend instead just add pkgs.neovim-nightly to your system.packages and install declaratively (with nixos-rebuild switch)

**Comment by blissdev** [comment]
I tried the variation you mentioned, with keeping the overlay in `configuration.nix` and then adding it to my `system.packages` and it looks like I end up with "0.4.4". Did I understand your suggestion correctly?

```
[demo@nixos:~]$ nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: 
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/jlfvykhy6ybpc3lp731cz0b03x9n1f7n-neovim-unwrapped-0.4.4/share/nvim
"

Run :checkhealth for more info
```

**Comment by mjlbach** [comment]
Yes, you need to make sure you call rebuild-switch, and not install any version of neovim via home-manager or via nix-env which would elid the one installed via configuration.nix

**Comment by blissdev** [comment]
Thanks, I appreciate the support here! I guess I accidentally installed neovim as root, and that is what was winning. Thanks so much for your time.

**Comment by blissdev** [comment]
Just one quick thing I noticed, curious if you could point me in the right direction. I noticed that if I reboot, `nvim` is gone. But if I run `rebuild-switch` then it installs again. Any ideas what I may be doing wrong there?

**Comment by mjlbach** [comment]
Nope, sorry. You'll probably want to ask on the nixos discourse or the IRC. I've never had that problem.
