### ISSUE TITLE
pass functionaltests on nixos

### ISSUE THREAD

**Issue by teto** [nix-community/neovim-nightly-overlay#95]
I was never able to pass the testsuite on nixos. the funny thing is that the list of failing test keeps changing
- https://github.com/neovim/neovim/pull/13744
- Right now I have the lsp plugin failing
```
- - [  ERROR   ] test/functional/plugin/lsp_spec.lua @ 918: LSP lsp._cmd_parts test should invalid cmd argument
test/helpers.lua:136: expected failure, but got success

stack traceback:
	test/helpers.lua:136: in function 'pcall_err_withfile'
	test/helpers.lua:159: in function 'pcall_err'
	test/functional/plugin/lsp_spec.lua:923: in function <test/functional/plugin/lsp_spec.lua:918>

**Comment by mjlbach** [comment]
That's funny, because I'm pretty sure our CI is showing that same failure for https://github.com/neovim/neovim/pull/13979 (which is obviously not on nixos haha)

**Comment by teto** [comment]
lulz I 've just had local issues with this PB happening on https://github.com/neovim/neovim/pull/13945 . It happened on a local master so I pushed but it passed CI xD

**Comment by Kranzes** [comment]
Out of the scope of this repo. This repo is only meant for providing an overlay and binary cache for nightly build by inheriting the nix code from upstream.
