### ISSUE TITLE
Document how to set configuration?

### ISSUE THREAD

**Issue by a-h** [nix-community/neovim-nightly-overlay#99]
I'm not sure whether it's an issue with nix-darwin, or my lack of nix skills, but I can't work out how to configure this overlay with a vimrc etc.

Could someone put an example in the repo please? I've documented my attempts of trying to run the nightly here: https://github.com/LnL7/nix-darwin/issues/316

**Comment by mjlbach** [comment]
This is a question best suited for discourse or the nix manual, pkgs.neovim-nightly is a drop-in replacement for wherever pkgs.neovim is called, there is nothing unique about using it.

**Comment by a-h** [comment]
Thanks, it doesn't seem like a drop-in replacement to me...

When I change from:

```nix
      (
	 pkgs.neovim.override {
	    vimAlias = true;
	    configure = {
	      packages.myPlugins = with pkgs.vimPlugins; {
		start = [
		  vim-go
		  vim-lastplace
		  vim-nix
		  coc-prettier
		  easygrep #dkprice/vim-easygrep
		  #nvim-lspconfig #https://neovim.io/doc/user/lsp.html#lsp-extension-example
		];
		opt = [];
	      };
	      customRC = builtins.readFile ./../dotfiles/.vimrc;
	  };
	}
      )
```

To:

```nix
      (
	 pkgs.neovim-nightly.override {
	    vimAlias = true;
	    configure = {
	      packages.myPlugins = with pkgs.vimPlugins; {
		start = [
		  vim-go
		  vim-lastplace
		  vim-nix
		  coc-prettier
		  easygrep #dkprice/vim-easygrep
		  #nvim-lspconfig #https://neovim.io/doc/user/lsp.html#lsp-extension-example
		];
		opt = [];
	      };
	      customRC = builtins.readFile ./../dotfiles/.vimrc;
	  };
	}
      )
```

I get an error:

> error: anonymous function at /nix/store/r85slpvs1z7gykc968bbsqy3dmcc1a5h-source/pkgs/applications/editors/neovim/default.nix:1:1 called with unexpected argument 'vimAlias', at /nix/store/r85slpvs1z7gykc968bbsqy3dmcc1a5h-source/lib/customisation.nix:79:63

I'll ask on the Discourse though!

**Comment by mjlbach** [comment]
Neovim nightly is an override for neovim-unwrapped, not neovim, so you need to write the wrapper if you want to use the other helper functions.

**Comment by teto** [comment]
@a-h I encourage you to use wrapNeovim or the home-manager plugin which exposes typed options to configure neovim.

**Comment by mjlbach** [comment]
@a-h The overlay now explicitly overrides neovim-unwrapped, so your original post should "just work"

**Comment by a-h** [comment]
Awesome, thanks so much @mjlbach. Here's the commit that's got me running Neovim nightly! https://github.com/a-h/dotfiles/commit/dd56c35908958a4abf727ab590421b93b071486e

**Comment by 573** [comment]
Pls reopen, does not work anymore, see https://github.com/573/nix-config-1/commit/a91916a48ba26fa555fd452947bc775d76548033, same error as OP.

**Comment by 573** [comment]
> Awesome, thanks so much @mjlbach. Here's the commit that's got me running Neovim nightly! [a-h/dotfiles@dd56c35](https://github.com/a-h/dotfiles/commit/dd56c35908958a4abf727ab590421b93b071486e)

you're using `neovim.override` not `neovim-nightly.override` there still ?
